---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cars-api
  name: cars-api-entrypoint
  namespace: default
spec:
  selector:
    serviceType: cars-api
  ports:
  - name: http
    nodePort: 30090
    port: 8084
    protocol: TCP
    targetPort: 8084
  type: NodePort