apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cars-api-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cars-api-v1
        version: "1.0.0"
    spec:
      containers:
      - name: cars-api-container
        image: leandropantoja/cars-api:1.0.0
        ports:
        - containerPort: 8084
