apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: cars-api-default
spec:
  destination:
    name: cars-api
    namespace: myproject
  precedence: 1
  route:
  - labels:
      version: 0.0.1
    weight: 100
