---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.metadata.name }}
  name: {{ .Values.metadata.name }}-entrypoint
  namespace: {{ .Values.labels.namespace }}
spec:
  selector:
    serviceType: {{ .Values.spec.selector.serviceType }}
  ports:
  - name: http
    nodePort: {{ .Values.service.nodePort }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  type: NodePort

